import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Deployed-terminal alignment: Geist + Geist Mono as the latin faces
// (self-hosted at build time via next/font; CJK falls back to the native
// system stack).
const geist = Geist({ subsets: ["latin"], variable: "--font-geist", display: "swap" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono", display: "swap" });
// Moved from the (dashboard) group layout with the shell (round 116).
const colorConvScript = `try{if(localStorage.getItem("aionis-colorconv")==="cn"){document.documentElement.dataset.colorconv="cn"}}catch(e){}`;
import { ThemeProvider } from "next-themes";
import { ThemeFade } from "@/components/theme-fade";
import { TooltipProvider } from "@/components/ui/tooltip";
import { I18nProvider } from "@/i18n/provider";
import { BackToTop } from "@/components/back-to-top";
import { LiquidGlassFilter } from "@/components/liquid-glass-filter";
import { TopNav } from "@/components/top-nav";
import "./globals.css";

// Typography is the native system stack (SF Pro on Apple, Segoe UI elsewhere,
// PingFang/YaHei for CJK) defined in globals.css — the Apple signature, no
// webfont approximation, zero network font cost.

// Shell (round 116, root-landing brief option B): the nav/main/BackToTop rail
// moved up from the (dashboard) group layout so `/` — now a real page, not a
// redirect shell — gets the same chrome as every route (not-found included).

export const viewport = {
  themeColor: "#0a0a0a",
};

export const metadata: Metadata = {
  metadataBase: new URL("https://rethymus.github.io/Aionis"),
  title: "Aionis — 反泄漏选股研究终端",
  description:
    "Anti-leakage stock-pick research terminal: stock-pick ranking, evidence wall, and power-floor monitor. Null is the intended outcome.",
  // Feed auto-discovery (round 181): <link rel="alternate" type="application/atom+xml">.
  alternates: {
    types: { "application/atom+xml": [{ url: "/atom.xml", title: "Aionis — Market News (EN/中文)" }] },
  },
  // Apple touch icon (round 189): iOS ignores the SVG favicon and the PWA
  // manifest for "Add to Home Screen" — it needs a PNG apple-touch-icon.
  // Committed static file (art = the OG card's green A tile; regenerated by
  // temporarily restoring an app/apple-icon.tsx ImageResponse route and
  // copying its build output). Static file, not a metadata route: the route
  // flavor emits an extensionless artifact that GitHub Pages would serve as
  // application/octet-stream.
  icons: {
    apple: [{ url: "/Aionis/apple-touch-icon.png", type: "image/png", sizes: "180x180" }],
  },
  openGraph: {
    title: "Aionis — 反泄漏选股研究终端",
    description:
      "Anti-leakage stock-pick research terminal. Personal research · non-investment advice.",
    type: "website",
    url: "https://rethymus.github.io/Aionis/",
  },
  twitter: {
    card: "summary_large_image",
    title: "Aionis — 反泄漏选股研究终端",
    description: "Anti-leakage stock-pick research terminal.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-CN"
      className={`${geist.variable} ${geistMono.variable} h-full antialiased font-sans`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {/* Speculation Rules (round 117, Chrome/Edge 121+ — ignored as inert
            JSON everywhere else): hover/pointerdown prerender of same-app
            navigations. This is a 1,500-page STATIC site with full-page
            navigations — Chrome's own docs call that the ideal use case.
            eagerness "moderate" = ~200ms hover / pointerdown, concurrency
            capped at 2 (FIFO) and auto-disabled under Save-Data / Preload
            off — polite by construction. Pattern pinned to /Aionis/* so
            outbound links never speculate. */}
        <script
          type="speculationrules"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              prerender: [{
                where: { href_matches: "/Aionis/*" },
                eagerness: "moderate",
              }],
            }),
          }}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <I18nProvider>
            <ThemeFade />
            <TooltipProvider>
              {/* Pre-paint application of the saved up/down color convention
                  (same pattern next-themes uses for theme): ships inside the
                  prerendered HTML and runs before hydration, so a CN-convention
                  user never sees a green-up flash. */}
              <script dangerouslySetInnerHTML={{ __html: colorConvScript }} />
              <div className="flex min-h-screen flex-col">
                <TopNav />
                {/* Chrome-path Liquid Glass lensing filter for the nav dropdown
                    (backdrop-filter: url(#liquid-glass-lens)); other browsers
                    keep the plain blur()/saturate() material from globals.css. */}
                <LiquidGlassFilter />
                {/* Aligned-site main rail: 1320px, px-5/py-8 (md:px-6). Sticky
                    descendants (hot-ticker strip) stay valid — no
                    overflow-hidden ancestor. */}
                <main className="mx-auto w-full max-w-[1320px] flex-1 px-5 py-8 md:px-6">
                  {children}
                </main>
                <BackToTop />
              </div>
            </TooltipProvider>
          </I18nProvider>
        </ThemeProvider>
      </body>
      {/* JSON-LD structured data (round 179): WebSite schema for search
          engine understanding — name, description, and the project's key
          stat (4 NULL verdicts) for rich result eligibility. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebSite",
            name: "Aionis",
            alternateName: "Aionis 反泄漏选股研究终端",
            description:
              "Anti-leakage quantitative-finance research terminal: frozen OOS picks, evidence wall, power-floor monitor. 4 NULL verdicts across B/C/D/E1 phases.",
            url: "https://rethymus.github.io/Aionis/",
          }),
        }}
      />
    </html>
  );
}
